---
#
# Ansible managed
#

name: Release to Ansible Galaxy

on:
  push:
    tags:
      - '*'
  schedule:
    - cron: '51 15 22 * *'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: galaxy
        uses: robertdebock/galaxy-action@1.0.1
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
